# Generated by Django 6.0 on 2025-12-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=15)),
                ('emp_doj', models.DateField(max_length=50)),
                ('emp_salary', models.IntegerField(max_length=50)),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
                ('emp_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_designation')),
            ],
        ),
    ]
