# Generated by Django 6.0 on 2026-01-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mealtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype_name', models.CharField(max_length=50)),
                ('meal_fromtime', models.DateField(max_length=50)),
                ('meal_totime', models.DateField(max_length=50)),
            ],
        ),
    ]
