# Generated by Django 6.0 on 2026-01-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_mealtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mealtype',
        ),
    ]
