# Generated by Django 6.0 on 2026-01-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory_name', models.CharField(max_length=50)),
            ],
        ),
    ]
