# Generated by Django 6.0 on 2026-01-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_foodcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_recipe',
        ),
    ]
