# Generated by Django 6.0 on 2026-01-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_delete_tbl_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_details', models.CharField(max_length=70)),
                ('recipe_file', models.FileField(upload_to='Assets/RecipeDocs')),
                ('foodcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_foodcategory')),
                ('mealtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_mealtype')),
            ],
        ),
    ]
