# Generated by Django 6.0 on 2026-01-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ingerdients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingerdients_name', models.CharField(max_length=50)),
                ('ingerdients_quantity', models.CharField(max_length=70)),
                ('ingerdients_remark', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_recipe')),
            ],
        ),
    ]
