# Generated by Django 6.0 on 2026-01-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_delete_tbl_ingerdients'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ingerdients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingerdients_name', models.CharField(max_length=50)),
                ('ingerdients_quantity', models.IntegerField(max_length=20)),
                ('ingerdients_remark', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_recipe')),
            ],
        ),
    ]
