# Generated by Django 6.0 on 2026-01-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_tbl_ingerdients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ingerdients',
        ),
    ]
