# Generated by Django 6.0 on 2026-01-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_tbl_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ingredients',
        ),
    ]
