# Generated by Django 6.0 on 2026-01-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_delete_tbl_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_name', models.CharField(max_length=50)),
                ('ingredients_quantity', models.CharField(max_length=50)),
                ('ingredients_remark', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_recipe')),
            ],
        ),
    ]
