# Generated by Django 6.0 on 2026-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_tbl_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_duration', models.CharField(max_length=50)),
                ('plan_details', models.CharField(max_length=70)),
                ('plan_amount', models.IntegerField(max_length=40)),
            ],
        ),
    ]
