# Generated by Django 6.0 on 2026-02-17 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_recipe',
            name='recipe_video',
            field=models.FileField(blank=True, null=True, upload_to='Assets/RecipeVideos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
    ]
