# Generated by Django 6.0 on 2026-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_recipe_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_plan',
            name='plan_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_plan',
            name='plan_details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_plan',
            name='plan_duration',
            field=models.IntegerField(),
        ),
    ]
