# Generated by Django 6.0 on 2026-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_alter_tbl_plan_plan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_recipe',
            name='diet_info',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
