# Generated by Django 6.0 on 2026-01-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
