# Generated by Django 6.0 on 2026-01-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
