# Generated by Django 6.0 on 2026-01-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_tbl_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stock',
            name='stock_count',
            field=models.IntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/GalleryDocs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product')),
            ],
        ),
    ]
