# Generated by Django 6.0 on 2026-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_alter_tbl_stock_stock_count_tbl_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
