# Generated by Django 6.0 on 2026-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_tbl_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='weight_unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
