# Generated by Django 6.0 on 2026-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_tbl_product_product_weight_tbl_product_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre')], max_length=10, null=True),
        ),
    ]
