# Generated by Django 6.0 on 2026-01-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_deliveryboy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_deliveryboy',
        ),
    ]
