# Generated by Django 6.0 on 2026-01-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_brand'),
        ('Guest', '0008_delete_tbl_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=50)),
                ('delivery_gender', models.CharField(max_length=50)),
                ('delivery_email', models.CharField(max_length=50)),
                ('delivery_contact', models.CharField(max_length=15)),
                ('delivery_address', models.CharField(max_length=50)),
                ('delivery_photo', models.FileField(upload_to='Assets/DeliveryboyDocs')),
                ('delivery_proof', models.FileField(upload_to='Assets/DeliveryboyDocs')),
                ('delivery_status', models.IntegerField(default=0)),
                ('delivery_password', models.CharField(max_length=50)),
                ('delivery_doj', models.DateField(auto_now_add=True)),
                ('delivery_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
