# Generated by Django 6.0 on 2026-01-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
