# Generated by Django 6.0 on 2026-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
