# Generated by Django 6.0 on 2026-02-09 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_plan'),
        ('Guest', '0011_delete_tbl_product'),
        ('Seller', '0007_alter_tbl_stock_stock_count_tbl_gallery'),
        ('User', '0004_tbl_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_datetime', models.DateTimeField(auto_now_add=True)),
                ('rating_content', models.CharField(max_length=50)),
                ('rating_value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
