# Generated by Django 6.0 on 2026-02-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_tbl_plan'),
        ('Seller', '0007_alter_tbl_stock_stock_count_tbl_gallery'),
        ('User', '0005_tbl_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_product'),
        ),
        migrations.AlterField(
            model_name='tbl_rating',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_recipe'),
        ),
    ]
