# Generated by Django 6.0 on 2026-02-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subscription',
        ),
    ]
